export const SWARAMS = {
    0: 'Sa',
    1: 'Ri1',
    2: 'Ri2',
    3: 'Ga2',
    4: 'Ga3',
    5: 'Ma1',
    6: 'Ma2',
    7: 'Pa',
    8: 'Da1',
    9: 'Da2',
    10: 'Ni2',
    11: 'Ni3'
};

// Abbreviated sargam display (S R G M P D N style)
const SARGAM_MAP = {
    'Sa': 'S', 'Ri1': 'R₁', 'Ri2': 'R₂', 'Ga1': 'G₁', 'Ga2': 'G₂',
    'Ri3': 'R₃', 'Ga3': 'G₃', 'Ma1': 'M₁', 'Ma2': 'M₂', 'Pa': 'P',
    'Da1': 'D₁', 'Da2': 'D₂', 'Ni1': 'N₁', 'Ni2': 'N₂', 'Da3': 'D₃',
    'Ni3': 'N₃'
};
export const toSargam = (note) => SARGAM_MAP[note] || note;

export const getSwaram = (frequency, saFrequency) => {
    if (!frequency || !saFrequency) return null;

    const ratio = frequency / saFrequency;
    const semitones = 12 * (Math.log(ratio) / Math.log(2));
    const roundedSemitones = Math.round(semitones);

    let interval = roundedSemitones % 12;
    if (interval < 0) interval += 12;

    return SWARAMS[interval];
};

// card header color cycles: 'maroon' | 'navy' | 'teal'
export const RAGAS = {
    // ── Ma₁ Melakartas (1–36) ─────────────────────────────────────────────
    'Kanakangi': {
        arohanam:     ['Sa', 'Ri1', 'Ga1', 'Ma1', 'Pa', 'Da1', 'Ni1', 'Sa'],
        avarohanam:   ['Sa', 'Ni1', 'Da1', 'Pa', 'Ma1', 'Ga1', 'Ri1', 'Sa'],
        type:         'Melakarta 1',
        mood:         'Austere · Ancient',
        description:  'The first raga of the entire system  ·  sparse, primordial, rarely performed. Its two consecutive lower notes give it a stark, almost primeval quality.',
        compositions: [],
        color:        'maroon',
        video:        "https://www.youtube.com/shorts/IA71flGF2KM",
    },
    'Ratnangi': {
        arohanam:     ['Sa', 'Ri1', 'Ga1', 'Ma1', 'Pa', 'Da1', 'Ni2', 'Sa'],
        avarohanam:   ['Sa', 'Ni2', 'Da1', 'Pa', 'Ma1', 'Ga1', 'Ri1', 'Sa'],
        type:         'Melakarta 2',
        mood:         'Meditative · Restrained',
        description:  'Subtle and inward-looking. The flat lower register and muted upper notes create a contemplative, almost wordless quality.',
        compositions: [],
        color:        'maroon',
        video:        "https://www.youtube.com/shorts/kxG7WShUip4",
    },
    'Ganamurti': {
        arohanam:     ['Sa', 'Ri1', 'Ga1', 'Ma1', 'Pa', 'Da1', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Da1', 'Pa', 'Ma1', 'Ga1', 'Ri1', 'Sa'],
        type:         'Melakarta 3',
        mood:         'Devotion · Reverence',
        description:  'Named for Ganapati (Gana + murti), suggesting auspicious beginnings. The bright Ni3 over the flat lower register creates a striking contrast.',
        compositions: [],
        color:        'maroon',
        video:        "https://www.youtube.com/shorts/S1OlbgC2NNw",
    },
    'Vanaspati': {
        arohanam:     ['Sa', 'Ri1', 'Ga1', 'Ma1', 'Pa', 'Da2', 'Ni2', 'Sa'],
        avarohanam:   ['Sa', 'Ni2', 'Da2', 'Pa', 'Ma1', 'Ga1', 'Ri1', 'Sa'],
        type:         'Melakarta 4',
        mood:         'Nature · Calm',
        description:  'Evokes the quiet of a forest  ·  flat lower notes, gentle upper register. Rarely heard, but carries a sense of deep natural stillness.',
        compositions: [],
        color:        'maroon',
        video:        "https://www.youtube.com/shorts/vH6qivcJJOM",
    },
    'Manavati': {
        arohanam:     ['Sa', 'Ri1', 'Ga1', 'Ma1', 'Pa', 'Da2', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Da2', 'Pa', 'Ma1', 'Ga1', 'Ri1', 'Sa'],
        type:         'Melakarta 5',
        mood:         'Dignity · Solemnity',
        description:  'A raga of quiet dignity. The flat Ri against the bright upper notes gives it a solemn, unhurried feeling.',
        compositions: [],
        color:        'maroon',
        video:        "https://www.youtube.com/shorts/XFTf-O-yvJw",
    },
    'Tanarupi': {
        arohanam:     ['Sa', 'Ri1', 'Ga1', 'Ma1', 'Pa', 'Ni2', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Ni2', 'Pa', 'Ma1', 'Ga1', 'Ri1', 'Sa'],
        type:         'Melakarta 6',
        mood:         'Unusual · Contemplative',
        description:  'One of the structurally unusual Melakartas  ·  the upper tetrachord has two consecutive semitones (Ni2-Ni3) mirroring the lower pair (Ri1-Ri2).',
        compositions: [],
        color:        'maroon',
        video:        "https://www.youtube.com/shorts/LBHKpmbiex4",
    },
    'Senavati': {
        arohanam:     ['Sa', 'Ri1', 'Ga2', 'Ma1', 'Pa', 'Da1', 'Ni1', 'Sa'],
        avarohanam:   ['Sa', 'Ni1', 'Da1', 'Pa', 'Ma1', 'Ga2', 'Ri1', 'Sa'],
        type:         'Melakarta 7',
        mood:         'Earnest · Devotional',
        description:  'The flat Ri and Ga2 lower tetrachord, combined with flat Da, gives this raga a grounded, unhurried devotional quality.',
        compositions: [],
        color:        'navy',
        video:        "https://www.youtube.com/watch?v=zw0c0U13i1A",
    },
    'Hanumatodi': {
        arohanam:     ['Sa', 'Ri1', 'Ga2', 'Ma1', 'Pa', 'Da1', 'Ni2', 'Sa'],
        avarohanam:   ['Sa', 'Ni2', 'Da1', 'Pa', 'Ma1', 'Ga2', 'Ri1', 'Sa'],
        type:         'Melakarta 8',
        mood:         'Pathos · Devotion',
        description:  'The parent of Todi  ·  one of the most beloved ragas in all of Carnatic music. Its deeply flat lower register holds you gently in longing. Morning performances are legendary.',
        compositions: ['Ninnukori  ·  Tyagaraja', 'Brovavamma  ·  Tyagaraja'],
        color:        'navy',
        video:        "https://www.youtube.com/watch?v=u-FSjbnawbk&list=RDu-FSjbnawbk&start_radio=1",
    },
    'Dhenuka': {
        arohanam:     ['Sa', 'Ri1', 'Ga2', 'Ma1', 'Pa', 'Da1', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Da1', 'Pa', 'Ma1', 'Ga2', 'Ri1', 'Sa'],
        type:         'Melakarta 9',
        mood:         'Melancholy · Grace',
        description:  'The sharp Ni3 over the deeply flat lower register creates an unexpected brightness  ·  like sunlight breaking through an overcast morning.',
        compositions: [],
        color:        'navy',
        video:        "https://www.youtube.com/watch?v=m9JRQhLbJIw",
    },
    'Natakapriya': {
        arohanam:     ['Sa', 'Ri1', 'Ga2', 'Ma1', 'Pa', 'Da2', 'Ni2', 'Sa'],
        avarohanam:   ['Sa', 'Ni2', 'Da2', 'Pa', 'Ma1', 'Ga2', 'Ri1', 'Sa'],
        type:         'Melakarta 10',
        mood:         'Drama · Pathos',
        description:  'Dramatic contrast between flat lower and middle register. Said to be suited for theatrical expression.',
        compositions: [],
        color:        'navy',
        video:        "https://www.youtube.com/shorts/HfiXKOVPZ0A",
    },
    'Kokilapriya': {
        arohanam:     ['Sa', 'Ri1', 'Ga2', 'Ma1', 'Pa', 'Da2', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Da2', 'Pa', 'Ma1', 'Ga2', 'Ri1', 'Sa'],
        type:         'Melakarta 11',
        mood:         'Birdsong · Lightness',
        description:  'Named for the koel (kokila). The flat lower register with a bright Da2-Ni3 upper tetrachord creates something lovely and surprising.',
        compositions: [],
        color:        'navy',
        video:        "https://www.youtube.com/watch?v=ll9kbKFk-mw&list=RDll9kbKFk-mw&start_radio=1",
    },
    'Rupavati': {
        arohanam:     ['Sa', 'Ri1', 'Ga2', 'Ma1', 'Pa', 'Da3', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Da3', 'Pa', 'Ma1', 'Ga2', 'Ri1', 'Sa'],
        type:         'Melakarta 12',
        mood:         'Beauty · Contemplation',
        description:  'Two consecutive upper semitones against the flat lower tetrachord. An unusual structural symmetry that gives it a reflective, aesthetic quality.',
        compositions: [],
        color:        'navy',
        video:        "https://www.youtube.com/shorts/foinxlB0prk",
    },
    'Gayakapriya': {
        arohanam:     ['Sa', 'Ri1', 'Ga3', 'Ma1', 'Pa', 'Da1', 'Ni1', 'Sa'],
        avarohanam:   ['Sa', 'Ni1', 'Da1', 'Pa', 'Ma1', 'Ga3', 'Ri1', 'Sa'],
        type:         'Melakarta 13',
        mood:         'Warmth · Sincerity',
        description:  'The combination of flat Ri with natural Ga3 is a signature sound  ·  warm and earnest. The flat Da cluster gives a tender quality.',
        compositions: [],
        color:        'teal',
        video:        "https://www.youtube.com/watch?v=wOcQS6s48Y8",
    },
    'Vakulabharanam': {
        arohanam:     ['Sa', 'Ri1', 'Ga3', 'Ma1', 'Pa', 'Da1', 'Ni2', 'Sa'],
        avarohanam:   ['Sa', 'Ni2', 'Da1', 'Pa', 'Ma1', 'Ga3', 'Ri1', 'Sa'],
        type:         'Melakarta 14',
        mood:         'Tender · Devotional',
        description:  'A raga of tender devotion  ·  flat Ri and Da against natural Ga. Rarely explored fully but carries a distinctive sweetness.',
        compositions: [],
        color:        'teal',
        video:        "https://www.youtube.com/watch?v=iY_S2C9Q3GY",
    },
    'Mayamalavagowla': {
        arohanam:     ['Sa', 'Ri1', 'Ga3', 'Ma1', 'Pa', 'Da1', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Da1', 'Pa', 'Ma1', 'Ga3', 'Ri1', 'Sa'],
        type:         'Melakarta 15',
        mood:         'Devotion · Pathos',
        description:  "The raga of morning prayers  ·  ancient, majestic, complete. Every music student's first Melakarta. The symmetry of Ri1/Da1 with Ga3/Ni3 gives it an eternal, timeless feeling.",
        compositions: ['Dorukuna Ituvanti  ·  Tyagaraja', 'Devi Niye Tunai  ·  Papanasam Sivan'],
        color:        'teal',
        video:        "https://www.youtube.com/watch?v=yeEJwbHDwXc",
    },
    'Chakravakam': {
        arohanam:     ['Sa', 'Ri1', 'Ga3', 'Ma1', 'Pa', 'Da2', 'Ni2', 'Sa'],
        avarohanam:   ['Sa', 'Ni2', 'Da2', 'Pa', 'Ma1', 'Ga3', 'Ri1', 'Sa'],
        type:         'Melakarta 16',
        mood:         'Serenity · Warmth',
        description:  'Parent of the beloved janya Chakravakam  ·  gentle and warm. The natural Ga with moderate upper notes creates a calm, even temperament.',
        compositions: [],
        color:        'teal',
        video:        "https://www.youtube.com/watch?v=vBh6Ejc49JY",
    },
    'Suryakantam': {
        arohanam:     ['Sa', 'Ri1', 'Ga3', 'Ma1', 'Pa', 'Da2', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Da2', 'Pa', 'Ma1', 'Ga3', 'Ri1', 'Sa'],
        type:         'Melakarta 17',
        mood:         'Solar · Radiant',
        description:  'Named for the sun  ·  the flat Ri against a bright upper tetrachord gives a luminous quality, like sunlight on still water.',
        compositions: [],
        color:        'teal',
        video:        "https://www.youtube.com/watch?v=Hkps35SAJb4",
    },
    'Hatakambari': {
        arohanam:     ['Sa', 'Ri1', 'Ga3', 'Ma1', 'Pa', 'Da3', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Da3', 'Pa', 'Ma1', 'Ga3', 'Ri1', 'Sa'],
        type:         'Melakarta 18',
        mood:         'Intensity · Focus',
        description:  'The consecutive Ni2-Ni3 in the upper register creates an unusual intensity. The combination with natural Ga is striking and memorable.',
        compositions: [],
        color:        'teal',
        video:        "https://www.youtube.com/watch?v=RC80kv8cFmw",
    },
    'Jhankaradhwani': {
        arohanam:     ['Sa', 'Ri2', 'Ga2', 'Ma1', 'Pa', 'Da1', 'Ni1', 'Sa'],
        avarohanam:   ['Sa', 'Ni1', 'Da1', 'Pa', 'Ma1', 'Ga2', 'Ri2', 'Sa'],
        type:         'Melakarta 19',
        mood:         'Resonance · Depth',
        description:  'The Da1-Da2 cluster in the upper register gives it an unusual resonant quality, like temple bells with a slight shadow.',
        compositions: [],
        color:        'maroon',
        video:        "https://www.youtube.com/watch?v=ID9_GCsPdhs",
    },
    'Natabhairavi': {
        arohanam:     ['Sa', 'Ri2', 'Ga2', 'Ma1', 'Pa', 'Da1', 'Ni2', 'Sa'],
        avarohanam:   ['Sa', 'Ni2', 'Da1', 'Pa', 'Ma1', 'Ga2', 'Ri2', 'Sa'],
        type:         'Melakarta 20',
        mood:         'Pathos · Grace',
        description:  'The mother of Bhairavi and parent to an entire universe of melancholic ragas. Vast, maternal, emotionally complete. Singing Natabhairavi feels like being held.',
        compositions: ['Mamava Pattabhirama  ·  Mysore Vasudevachar', 'Bhogeendra Sayana  ·  Dikshitar'],
        color:        'maroon',
        video:        "https://www.youtube.com/watch?v=3QFlAd0xS-U",
    },
    'Keeravani': {
        arohanam:     ['Sa', 'Ri2', 'Ga2', 'Ma1', 'Pa', 'Da1', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Da1', 'Pa', 'Ma1', 'Ga2', 'Ri2', 'Sa'],
        type:         'Melakarta 21',
        mood:         'Longing · Beauty',
        description:  'The same as a natural minor scale with sharp seventh  ·  strikingly close to Western harmonic minor. It has a quality of yearning that resolves into wonder.',
        compositions: [],
        color:        'maroon',
        video:        'https://www.youtube.com/shorts/oUvswrCsuHc',
    },
    'Kharaharapriya': {
        arohanam:     ['Sa', 'Ri2', 'Ga2', 'Ma1', 'Pa', 'Da2', 'Ni2', 'Sa'],
        avarohanam:   ['Sa', 'Ni2', 'Da2', 'Pa', 'Ma1', 'Ga2', 'Ri2', 'Sa'],
        type:         'Melakarta 22',
        mood:         'Sweetness · Bhakti',
        description:  "The \"everyman's raga\"  ·  widely loved, sung in homes and concert halls alike. Its gentle, natural quality makes it feel like being understood. Parent of Abheri, Nayaki, and many more.",
        compositions: ['Ksheerasagara Shayana  ·  Tyagaraja', 'Sri Navagraha Kirtanam  ·  Dikshitar'],
        color:        'maroon',
        video:        "https://www.youtube.com/watch?v=WmhVmWEas3s",
    },
    'Gowrimanohari': {
        arohanam:     ['Sa', 'Ri2', 'Ga2', 'Ma1', 'Pa', 'Da2', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Da2', 'Pa', 'Ma1', 'Ga2', 'Ri2', 'Sa'],
        type:         'Melakarta 23',
        mood:         'Elegance · Devotion',
        description:  'Named for Gauri (Parvati). The flat Ga against bright Da2-Ni3 creates an elegant, feminine quality  ·  graceful and devotional.',
        compositions: [],
        color:        'maroon',
        video:        "https://www.youtube.com/watch?v=D_Ep_YW4qlU",
    },
    'Varunapriya': {
        arohanam:     ['Sa', 'Ri2', 'Ga2', 'Ma1', 'Pa', 'Da3', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Da3', 'Pa', 'Ma1', 'Ga2', 'Ri2', 'Sa'],
        type:         'Melakarta 24',
        mood:         'Water · Flow',
        description:  'Named for Varuna, god of waters. The flowing consecutive upper semitones suggest water in motion  ·  deep below, moving above.',
        compositions: [],
        color:        'maroon',
        video:        "https://www.youtube.com/watch?v=Z9SXoDqHq5I",
    },
    'Mararanjani': {
        arohanam:     ['Sa', 'Ri2', 'Ga3', 'Ma1', 'Pa', 'Da1', 'Ni1', 'Sa'],
        avarohanam:   ['Sa', 'Ni1', 'Da1', 'Pa', 'Ma1', 'Ga3', 'Ri2', 'Sa'],
        type:         'Melakarta 25',
        mood:         'Joy · Lightness',
        description:  'The bright natural Ga3 with Ri2 in the lower register and the unusual Da cluster gives a surprisingly playful, cheerful feeling.',
        compositions: [],
        color:        'navy',
        video:        "https://www.youtube.com/watch?v=54xSlsa_IB0",
    },
    'Charukesi': {
        arohanam:     ['Sa', 'Ri2', 'Ga3', 'Ma1', 'Pa', 'Da1', 'Ni2', 'Sa'],
        avarohanam:   ['Sa', 'Ni2', 'Da1', 'Pa', 'Ma1', 'Ga3', 'Ri2', 'Sa'],
        type:         'Melakarta 26',
        mood:         'Heroism · Pathos',
        description:  'An extraordinary raga  ·  bright Ga3 shadowed by flat Da1 and Ni2. It feels like courage in the face of loss, or joy carrying grief within it. One of the most emotionally complex Melakartas.',
        compositions: ['Sarasijanabha  ·  Dikshitar'],
        color:        'navy',
        video:        "https://www.youtube.com/watch?v=USiE_aD3E3g",
    },
    'Sarasangi': {
        arohanam:     ['Sa', 'Ri2', 'Ga3', 'Ma1', 'Pa', 'Da1', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Da1', 'Pa', 'Ma1', 'Ga3', 'Ri2', 'Sa'],
        type:         'Melakarta 27',
        mood:         'Devotion · Serenity',
        description:  'Natural Ga3 and Ni3 with flat Da1 creates a distinctive gentle tension. Clear and devotional in character.',
        compositions: [],
        color:        'navy',
        video:        "https://www.youtube.com/shorts/FnHF76wiEIs",
    },
    'Harikambhoji': {
        arohanam:     ['Sa', 'Ri2', 'Ga3', 'Ma1', 'Pa', 'Da2', 'Ni2', 'Sa'],
        avarohanam:   ['Sa', 'Ni2', 'Da2', 'Pa', 'Ma1', 'Ga3', 'Ri2', 'Sa'],
        type:         'Melakarta 28',
        mood:         'Abundance · Devotion',
        description:  'One of the most generative Melakartas  ·  parent to Kamboji, Mohanam, Khamas, Bilahari, and dozens of other beloved janyas. Rich, warm, and welcoming.',
        compositions: ['Sri Nathadi Guruguhadi  ·  Dikshitar'],
        color:        'navy',
        video:        "https://www.youtube.com/watch?v=g6EzTzuEriw",
    },
    'Dheerasankarabharanam': {
        arohanam:     ['Sa', 'Ri2', 'Ga3', 'Ma1', 'Pa', 'Da2', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Da2', 'Pa', 'Ma1', 'Ga3', 'Ri2', 'Sa'],
        type:         'Melakarta 29',
        mood:         'Grandeur · Devotion',
        description:  "All natural notes  ·  the \"Western Major scale\" of Carnatic music. Universally loved, capable of expressing the entire range of human emotion. Tyagaraja's most triumphant compositions live here.",
        compositions: ['Endaro Mahanubhavulu  ·  Tyagaraja'],
        color:        'navy',
        video:        "https://www.youtube.com/watch?v=7nbFmGJOpH8",
    },
    'Naganandini': {
        arohanam:     ['Sa', 'Ri2', 'Ga3', 'Ma1', 'Pa', 'Da3', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Da3', 'Pa', 'Ma1', 'Ga3', 'Ri2', 'Sa'],
        type:         'Melakarta 30',
        mood:         'Serpentine · Mystical',
        description:  "Named for the divine serpent. The consecutive upper semitones feel sinuous and hypnotic, moving in ways you don't quite expect.",
        compositions: [],
        color:        'navy',
        video:        "https://www.youtube.com/watch?v=K8WAYPwQc-c",
    },
    'Yagapriya': {
        arohanam:     ['Sa', 'Ri3', 'Ga3', 'Ma1', 'Pa', 'Da1', 'Ni1', 'Sa'],
        avarohanam:   ['Sa', 'Ni1', 'Da1', 'Pa', 'Ma1', 'Ga3', 'Ri3', 'Sa'],
        type:         'Melakarta 31',
        mood:         'Ritual · Ancient',
        description:  'The R5 rows begin with Ga2 (Ri3) where Ri would normally be  ·  giving a strikingly compressed lower register. Named for fire rituals (yagas), it has an ancient, ceremonial quality.',
        compositions: [],
        color:        'teal',
        video:        "https://www.youtube.com/watch?v=jGQ-URkjU3E",
    },
    'Ragavardhini': {
        arohanam:     ['Sa', 'Ri3', 'Ga3', 'Ma1', 'Pa', 'Da1', 'Ni2', 'Sa'],
        avarohanam:   ['Sa', 'Ni2', 'Da1', 'Pa', 'Ma1', 'Ga3', 'Ri3', 'Sa'],
        type:         'Melakarta 32',
        mood:         'Richness · Growth',
        description:  'Named "raga-increaser"  ·  as if it contains within it the seed of all ragas. The compressed lower tetrachord against a gentle upper register has unexpected richness.',
        compositions: [],
        color:        'teal',
        video:        "https://www.youtube.com/watch?v=CV_iKRWHtUs",
    },
    'Gangeyabhushani': {
        arohanam:     ['Sa', 'Ri3', 'Ga3', 'Ma1', 'Pa', 'Da1', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Da1', 'Pa', 'Ma1', 'Ga3', 'Ri3', 'Sa'],
        type:         'Melakarta 33',
        mood:         'Sacred · Flowing',
        description:  'Named for the ornament of the Ganges  ·  the sharp Ni3 over flat Da1, combined with the consecutive lower Ga notes, gives it a sacred, flowing quality.',
        compositions: [],
        color:        'teal',
        video:        "https://www.youtube.com/watch?v=0pwaB8Reu2k",
    },
    'Vagadheeswari': {
        arohanam:     ['Sa', 'Ri3', 'Ga3', 'Ma1', 'Pa', 'Da2', 'Ni2', 'Sa'],
        avarohanam:   ['Sa', 'Ni2', 'Da2', 'Pa', 'Ma1', 'Ga3', 'Ri3', 'Sa'],
        type:         'Melakarta 34',
        mood:         'Speech · Wisdom',
        description:  'Named for Saraswati, goddess of speech and learning. Its even temperament and balanced notes suggest eloquence and knowledge.',
        compositions: [],
        color:        'teal',
        video:        "https://www.youtube.com/watch?v=sluPZ-IHLU8",
    },
    'Shulini': {
        arohanam:     ['Sa', 'Ri3', 'Ga3', 'Ma1', 'Pa', 'Da2', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Da2', 'Pa', 'Ma1', 'Ga3', 'Ri3', 'Sa'],
        type:         'Melakarta 35',
        mood:         'Power · Sharpness',
        description:  "Named for Shiva's trident  ·  the bright upper tetrachord with the compressed lower register creates something powerful and incisive.",
        compositions: [],
        color:        'teal',
        video:        "https://www.youtube.com/watch?v=JtiONAdXJOo",
    },
    'Chalanata': {
        arohanam:     ['Sa', 'Ri3', 'Ga3', 'Ma1', 'Pa', 'Ni2', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Ni2', 'Pa', 'Ma1', 'Ga3', 'Ri3', 'Sa'],
        type:         'Melakarta 36',
        mood:         'Movement · Dance',
        description:  'The final Ma1 Melakarta  ·  named for movement in dance. Consecutive semitones in both lower and upper registers create a distinctive stepping quality.',
        compositions: [],
        color:        'teal',
        video:        "https://www.youtube.com/watch?v=c1mx-qVo0ks",
    },

    // ── Ma₂ Melakartas (37–72) ────────────────────────────────────────────
    'Salagam': {
        arohanam:     ['Sa', 'Ri1', 'Ga1', 'Ma2', 'Pa', 'Da1', 'Ni1', 'Sa'],
        avarohanam:   ['Sa', 'Ni1', 'Da1', 'Pa', 'Ma2', 'Ga1', 'Ri1', 'Sa'],
        type:         'Melakarta 37',
        mood:         'Depth · Gravity',
        description:  'The sharp Ma2 against flat Ri and flat Da creates a gravity and depth that feels different from its Ma1 counterparts. The beginning of the Prati Madhyamam half.',
        compositions: [],
        color:        'maroon',
        video:        "https://www.youtube.com/watch?v=bUYoL17nhu0",
    },
    'Jalarnavam': {
        arohanam:     ['Sa', 'Ri1', 'Ga1', 'Ma2', 'Pa', 'Da1', 'Ni2', 'Sa'],
        avarohanam:   ['Sa', 'Ni2', 'Da1', 'Pa', 'Ma2', 'Ga1', 'Ri1', 'Sa'],
        type:         'Melakarta 38',
        mood:         'Ocean · Vastness',
        description:  'Named "ocean of water"  ·  the Ma2 gives a sense of vastness and depth that the flat surrounding notes make feel even more spacious.',
        compositions: [],
        color:        'maroon',
        video:        "https://www.youtube.com/watch?v=Vma4c5X-Eyg",
    },
    'Jhalavarali': {
        arohanam:     ['Sa', 'Ri1', 'Ga1', 'Ma2', 'Pa', 'Da1', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Da1', 'Pa', 'Ma2', 'Ga1', 'Ri1', 'Sa'],
        type:         'Melakarta 39',
        mood:         'Antiquity · Depth',
        description:  'An unusual combination  ·  flat lower notes with sharp Ma2 and natural Ni3. Rarely performed but carries a sense of great antiquity.',
        compositions: [],
        color:        'maroon',
        video:        "https://www.youtube.com/watch?v=Tslljtf80OU",
    },
    'Navaneetam': {
        arohanam:     ['Sa', 'Ri1', 'Ga1', 'Ma2', 'Pa', 'Da2', 'Ni2', 'Sa'],
        avarohanam:   ['Sa', 'Ni2', 'Da2', 'Pa', 'Ma2', 'Ga1', 'Ri1', 'Sa'],
        type:         'Melakarta 40',
        mood:         'Gentleness · Freshness',
        description:  'Named for fresh butter (navaneetam)  ·  soft and smooth. The Ma2 brings sharpness to an otherwise gentle raga.',
        compositions: [],
        color:        'maroon',
        video:        "https://www.youtube.com/shorts/uTl3lqQIVYM",
    },
    'Pavani': {
        arohanam:     ['Sa', 'Ri1', 'Ga1', 'Ma2', 'Pa', 'Da2', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Da2', 'Pa', 'Ma2', 'Ga1', 'Ri1', 'Sa'],
        type:         'Melakarta 41',
        mood:         'Purity · Wind',
        description:  'Named for purity and the wind. The Ma2 with bright upper notes brings a clear, airy quality despite the flat lower register.',
        compositions: [],
        color:        'maroon',
        video:        "https://www.youtube.com/shorts/dLn0cEOsirU",
    },
    'Raghupriya': {
        arohanam:     ['Sa', 'Ri1', 'Ga1', 'Ma2', 'Pa', 'Ni2', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Ni2', 'Pa', 'Ma2', 'Ga1', 'Ri1', 'Sa'],
        type:         'Melakarta 42',
        mood:         'Majesty · Unusual',
        description:  'Named "dear to Raghu" (an epithet of Rama). Consecutive semitone pairs in both tetrachords with sharp Ma  ·  structurally unique and surprisingly stately.',
        compositions: [],
        color:        'maroon',
        video:        "https://www.youtube.com/shorts/4IcZ8zWhz6A",
    },
    'Gavambhodi': {
        arohanam:     ['Sa', 'Ri1', 'Ga2', 'Ma2', 'Pa', 'Da1', 'Ni1', 'Sa'],
        avarohanam:   ['Sa', 'Ni1', 'Da1', 'Pa', 'Ma2', 'Ga2', 'Ri1', 'Sa'],
        type:         'Melakarta 43',
        mood:         'Depth · Introspection',
        description:  'Flat Ri, flat Ga, and flat Da against the sharp Ma  ·  an unusual mix that creates deep introspection and a sense of searching.',
        compositions: [],
        color:        'navy',
        video:        "https://www.youtube.com/shorts/9wTbJfW46yM",
    },
    'Bhavapriya': {
        arohanam:     ['Sa', 'Ri1', 'Ga2', 'Ma2', 'Pa', 'Da1', 'Ni2', 'Sa'],
        avarohanam:   ['Sa', 'Ni2', 'Da1', 'Pa', 'Ma2', 'Ga2', 'Ri1', 'Sa'],
        type:         'Melakarta 44',
        mood:         'Emotion · Longing',
        description:  'Named "dear to emotions." The Ma2 brings an elevated longing to the otherwise plaintive flat notes  ·  like yearning for something transcendent.',
        compositions: [],
        color:        'navy',
        video:        "https://www.youtube.com/shorts/WDSgl8ik7-s",
    },
    'Shubhapantuvarali': {
        arohanam:     ['Sa', 'Ri1', 'Ga2', 'Ma2', 'Pa', 'Da1', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Da1', 'Pa', 'Ma2', 'Ga2', 'Ri1', 'Sa'],
        type:         'Melakarta 45',
        mood:         'Ancient · Devotion',
        description:  'Deep, ancient, almost Sanskrit in its seriousness. Flat Ri, Ga, Da against sharp Ma and Ni3  ·  a combination that feels like it comes from another era. Rare and unforgettable.',
        compositions: ['Kamakshi  ·  Dikshitar'],
        color:        'navy',
        video:        "https://www.youtube.com/watch?v=ciaUYI0-TEI",
    },
    'Shadvidhamargini': {
        arohanam:     ['Sa', 'Ri1', 'Ga2', 'Ma2', 'Pa', 'Da2', 'Ni2', 'Sa'],
        avarohanam:   ['Sa', 'Ni2', 'Da2', 'Pa', 'Ma2', 'Ga2', 'Ri1', 'Sa'],
        type:         'Melakarta 46',
        mood:         'Clarity · Path',
        description:  'Named for the "six paths." The sharp Ma2 with otherwise moderate notes creates an unusually clear-eyed feeling.',
        compositions: [],
        color:        'navy',
        video:        "https://www.youtube.com/watch?v=KTdX38Syars",
    },
    'Suvarnangi': {
        arohanam:     ['Sa', 'Ri1', 'Ga2', 'Ma2', 'Pa', 'Da2', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Da2', 'Pa', 'Ma2', 'Ga2', 'Ri1', 'Sa'],
        type:         'Melakarta 47',
        mood:         'Golden · Warmth',
        description:  'Named "golden-bodied." The flat Ri and Ga with bright upper notes and sharp Ma create a golden, glowing quality.',
        compositions: [],
        color:        'navy',
        video:        "https://www.youtube.com/watch?v=kX3Hjxgx12g",
    },
    'Divyamani': {
        arohanam:     ['Sa', 'Ri1', 'Ga2', 'Ma2', 'Pa', 'Da3', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Da3', 'Pa', 'Ma2', 'Ga2', 'Ri1', 'Sa'],
        type:         'Melakarta 48',
        mood:         'Divine Gem · Lustre',
        description:  'Named "divine jewel." The consecutive upper semitones combined with sharp Ma and flat lower register create something genuinely gem-like  ·  brilliant and rare.',
        compositions: [],
        color:        'navy',
        video:        "https://www.youtube.com/watch?v=Xv4em0sPcsc",
    },
    'Dhavalambari': {
        arohanam:     ['Sa', 'Ri1', 'Ga3', 'Ma2', 'Pa', 'Da1', 'Ni1', 'Sa'],
        avarohanam:   ['Sa', 'Ni1', 'Da1', 'Pa', 'Ma2', 'Ga3', 'Ri1', 'Sa'],
        type:         'Melakarta 49',
        mood:         'White · Pure',
        description:  'Named "white-robed"  ·  the sharp Ma2 and natural Ga3 against flat Ri and flat Da creates a bright, pure quality.',
        compositions: [],
        color:        'teal',
        video:        "https://www.youtube.com/watch?v=Jqj1EWxzSEs",
    },
    'Namanarayani': {
        arohanam:     ['Sa', 'Ri1', 'Ga3', 'Ma2', 'Pa', 'Da1', 'Ni2', 'Sa'],
        avarohanam:   ['Sa', 'Ni2', 'Da1', 'Pa', 'Ma2', 'Ga3', 'Ri1', 'Sa'],
        type:         'Melakarta 50',
        mood:         'Devotion · Reverence',
        description:  'Named for saluting Narayana. The Ma2 adds a devotional intensity to the Ri1-Ga3 combination.',
        compositions: [],
        color:        'teal',
        video:        "https://www.youtube.com/watch?v=WJwN4I3kKqs",
    },
    'Kamavardhini': {
        arohanam:     ['Sa', 'Ri1', 'Ga3', 'Ma2', 'Pa', 'Da1', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Da1', 'Pa', 'Ma2', 'Ga3', 'Ri1', 'Sa'],
        type:         'Melakarta 51',
        mood:         'Urgency · Devotion',
        description:  'Also known as Panthuvarali  ·  the flat Ri beside the sharp Ma2 creates a tension that feels urgent and searching. One of the most frequently performed Ma2 ragas.',
        compositions: ['Sri Kamalambike  ·  Dikshitar'],
        color:        'teal',
        video:        "https://www.youtube.com/watch?v=2KAK8Rb5c4s",
    },
    'Ramapriya': {
        arohanam:     ['Sa', 'Ri1', 'Ga3', 'Ma2', 'Pa', 'Da2', 'Ni2', 'Sa'],
        avarohanam:   ['Sa', 'Ni2', 'Da2', 'Pa', 'Ma2', 'Ga3', 'Ri1', 'Sa'],
        type:         'Melakarta 52',
        mood:         'Tenderness · Bhakti',
        description:  'Named "dear to Rama." The gentle upper tetrachord with bright Ma2 and flat Ri gives a warm, devotional feeling.',
        compositions: [],
        color:        'teal',
        video:        "https://www.youtube.com/watch?v=XgZDvdzb9Gw",
    },
    'Gamanashrama': {
        arohanam:     ['Sa', 'Ri1', 'Ga3', 'Ma2', 'Pa', 'Da2', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Da2', 'Pa', 'Ma2', 'Ga3', 'Ri1', 'Sa'],
        type:         'Melakarta 53',
        mood:         'Elevation · Brightness',
        description:  'The flat Ri1 combined with natural Ga3, sharp Ma2, and bright upper tetrachord creates a striking elevation  ·  like watching a sunrise from a mountaintop ashram.',
        compositions: [],
        color:        'teal',
        video:        "https://www.youtube.com/watch?v=p80-wIf6Ap4",
    },
    'Vishwambhari': {
        arohanam:     ['Sa', 'Ri1', 'Ga3', 'Ma2', 'Pa', 'Da3', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Da3', 'Pa', 'Ma2', 'Ga3', 'Ri1', 'Sa'],
        type:         'Melakarta 54',
        mood:         'Universal · Sustaining',
        description:  'Named "sustainer of the universe." Consecutive upper semitones with sharp Ma and flat Ri  ·  expansive and all-encompassing in character.',
        compositions: [],
        color:        'teal',
        video:        "https://www.youtube.com/watch?v=HVfSAv4KTeY",
    },
    'Shamalangi': {
        arohanam:     ['Sa', 'Ri2', 'Ga2', 'Ma2', 'Pa', 'Da1', 'Ni1', 'Sa'],
        avarohanam:   ['Sa', 'Ni1', 'Da1', 'Pa', 'Ma2', 'Ga2', 'Ri2', 'Sa'],
        type:         'Melakarta 55',
        mood:         'Dark Beauty · Mystery',
        description:  'Flat Ga2 and flat Da cluster against sharp Ma2  ·  the combination creates a mysteriously beautiful, twilight feeling.',
        compositions: [],
        color:        'maroon',
        video:        "https://www.youtube.com/watch?v=zfg1d8im3DY",
    },
    'Shanmukhapriya': {
        arohanam:     ['Sa', 'Ri2', 'Ga2', 'Ma2', 'Pa', 'Da1', 'Ni2', 'Sa'],
        avarohanam:   ['Sa', 'Ni2', 'Da1', 'Pa', 'Ma2', 'Ga2', 'Ri2', 'Sa'],
        type:         'Melakarta 56',
        mood:         'Vivid · Festive',
        description:  'Named for Shanmukha (Murugan). Widely used in film music  ·  its Ma2 against Ga2 gives it a vivid, almost cinematic quality. One of the more recognizable Ma2 ragas.',
        compositions: [],
        color:        'maroon',
        video:        "https://www.youtube.com/watch?v=VEjmKraGdSg",
    },
    'Simhendramadhyamam': {
        arohanam:     ['Sa', 'Ri2', 'Ga2', 'Ma2', 'Pa', 'Da1', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Da1', 'Pa', 'Ma2', 'Ga2', 'Ri2', 'Sa'],
        type:         'Melakarta 57',
        mood:         'Lion-like · Bold',
        description:  'Named "lion in the middle"  ·  the sharp Ma2 and sharp Ni3 against flat Ga2 and flat Da1 gives it a bold, contrasting strength.',
        compositions: [],
        color:        'maroon',
        video:        "https://www.youtube.com/watch?v=qoUwmLciWlg",
    },
    'Hemavati': {
        arohanam:     ['Sa', 'Ri2', 'Ga2', 'Ma2', 'Pa', 'Da2', 'Ni2', 'Sa'],
        avarohanam:   ['Sa', 'Ni2', 'Da2', 'Pa', 'Ma2', 'Ga2', 'Ri2', 'Sa'],
        type:         'Melakarta 58',
        mood:         'Gold · Warmth',
        description:  'Named for golden snow (Hema = gold). The Ma2 brings a warmth to what would otherwise be a pensive scale.',
        compositions: [],
        color:        'maroon',
        video:        "https://www.youtube.com/watch?v=IRAEJG2dbW4",
    },
    'Dharmavati': {
        arohanam:     ['Sa', 'Ri2', 'Ga2', 'Ma2', 'Pa', 'Da2', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Da2', 'Pa', 'Ma2', 'Ga2', 'Ri2', 'Sa'],
        type:         'Melakarta 59',
        mood:         'Righteous · Steady',
        description:  'Named for righteousness (dharma). The Ma2 and Ni3 over flat Ga2 creates a firm, principled, clear quality.',
        compositions: [],
        color:        'maroon',
        video:        "https://www.youtube.com/watch?v=MyRrqDXQ_JQ",
    },
    'Neetimati': {
        arohanam:     ['Sa', 'Ri2', 'Ga2', 'Ma2', 'Pa', 'Da3', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Da3', 'Pa', 'Ma2', 'Ga2', 'Ri2', 'Sa'],
        type:         'Melakarta 60',
        mood:         'Justice · Principle',
        description:  'Named "one who has ethics." Consecutive upper semitones with sharp Ma  ·  a raga of principled, deliberate movement.',
        compositions: [],
        color:        'maroon',
        video:        "https://www.youtube.com/watch?v=Gm0AVdNjaHc",
    },
    'Kantamani': {
        arohanam:     ['Sa', 'Ri2', 'Ga3', 'Ma2', 'Pa', 'Da1', 'Ni1', 'Sa'],
        avarohanam:   ['Sa', 'Ni1', 'Da1', 'Pa', 'Ma2', 'Ga3', 'Ri2', 'Sa'],
        type:         'Melakarta 61',
        mood:         'Gem · Vibrancy',
        description:  'Named "gem jewel." Bright Ga3 and sharp Ma2 against flat Da cluster  ·  vivid and glittering.',
        compositions: [],
        color:        'navy',
        video:        "https://www.youtube.com/watch?v=JtfPycCAVyw",
    },
    'Rishabhapriya': {
        arohanam:     ['Sa', 'Ri2', 'Ga3', 'Ma2', 'Pa', 'Da1', 'Ni2', 'Sa'],
        avarohanam:   ['Sa', 'Ni2', 'Da1', 'Pa', 'Ma2', 'Ga3', 'Ri2', 'Sa'],
        type:         'Melakarta 62',
        mood:         'Nobility · Grace',
        description:  "Named \"dear to Rishaba\" (Nandi, Shiva's vehicle). Natural Ga3 with sharp Ma2 and flat Da  ·  graceful and noble.",
        compositions: [],
        color:        'navy',
        video:        "https://www.youtube.com/watch?v=Z-uVVESsg9Q",
    },
    'Latangi': {
        arohanam:     ['Sa', 'Ri2', 'Ga3', 'Ma2', 'Pa', 'Da1', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Da1', 'Pa', 'Ma2', 'Ga3', 'Ri2', 'Sa'],
        type:         'Melakarta 63',
        mood:         'Feminine · Grace',
        description:  'Named for a graceful woman (latangi). Natural Ga3 and Ni3 with sharp Ma2 and flat Da creates a striking, elegant quality.',
        compositions: [],
        color:        'navy',
        video:        "https://www.youtube.com/watch?v=s8qS30EQ96o",
    },
    'Vachaspati': {
        arohanam:     ['Sa', 'Ri2', 'Ga3', 'Ma2', 'Pa', 'Da2', 'Ni2', 'Sa'],
        avarohanam:   ['Sa', 'Ni2', 'Da2', 'Pa', 'Ma2', 'Ga3', 'Ri2', 'Sa'],
        type:         'Melakarta 64',
        mood:         'Eloquence · Wisdom',
        description:  'Named for Brihaspati, the god of wisdom and speech. Natural Ga3 with sharp Ma2 and gentle upper notes  ·  articulate and wise.',
        compositions: [],
        color:        'navy',
        video:        "https://www.youtube.com/watch?v=OWdp9rlRp4E",
    },
    'Mechakalyani': {
        arohanam:     ['Sa', 'Ri2', 'Ga3', 'Ma2', 'Pa', 'Da2', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Da2', 'Pa', 'Ma2', 'Ga3', 'Ri2', 'Sa'],
        type:         'Melakarta 65',
        mood:         'Serenity · Devotion',
        description:  'The luminous parent of Kalyani  ·  the sharpened Ma2 gives everything a soaring, golden-evening quality. One of the most performed Melakartas, especially at dusk.',
        compositions: ['Nidhi Chala Sukhama  ·  Tyagaraja', 'Kamalamba Navavarana  ·  Dikshitar'],
        color:        'navy',
        video:        "https://www.youtube.com/watch?v=3MPHEEbUxnU",
    },
    'Chitrambari': {
        arohanam:     ['Sa', 'Ri2', 'Ga3', 'Ma2', 'Pa', 'Da3', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Da3', 'Pa', 'Ma2', 'Ga3', 'Ri2', 'Sa'],
        type:         'Melakarta 66',
        mood:         'Vivid · Rich',
        description:  'Named "dressed in pictures"  ·  the consecutive upper notes with sharp Ma2 and natural Ga3 create a vivid, richly ornamented feeling.',
        compositions: [],
        color:        'navy',
        video:        "https://www.youtube.com/watch?v=VJZLO_HUEkw",
    },
    'Sucharitra': {
        arohanam:     ['Sa', 'Ri3', 'Ga3', 'Ma2', 'Pa', 'Da1', 'Ni1', 'Sa'],
        avarohanam:   ['Sa', 'Ni1', 'Da1', 'Pa', 'Ma2', 'Ga3', 'Ri3', 'Sa'],
        type:         'Melakarta 67',
        mood:         'Virtue · Character',
        description:  'Named "one with good character." The compressed lower register with sharp Ma2 and flat Da cluster  ·  rare and characterful.',
        compositions: [],
        color:        'teal',
        video:        "https://www.youtube.com/watch?v=GkBtjDltP0g",
    },
    'Jyotiswarupini': {
        arohanam:     ['Sa', 'Ri3', 'Ga3', 'Ma2', 'Pa', 'Da1', 'Ni2', 'Sa'],
        avarohanam:   ['Sa', 'Ni2', 'Da1', 'Pa', 'Ma2', 'Ga3', 'Ri3', 'Sa'],
        type:         'Melakarta 68',
        mood:         'Light · Radiance',
        description:  'Named "embodiment of light." Sharp Ma2 against the compressed lower tetrachord creates a luminous quality  ·  light in the darkness.',
        compositions: [],
        color:        'teal',
        video:        "https://www.youtube.com/shorts/GlzSHos6dAs",
    },
    'Dhatuvardani': {
        arohanam:     ['Sa', 'Ri3', 'Ga3', 'Ma2', 'Pa', 'Da1', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Da1', 'Pa', 'Ma2', 'Ga3', 'Ri3', 'Sa'],
        type:         'Melakarta 69',
        mood:         'Growth · Elements',
        description:  'Named "increaser of minerals/elements." The sharp Ni3 and Ma2 over flat lower notes create a sense of growth and elemental force.',
        compositions: [],
        color:        'teal',
        video:        "https://www.youtube.com/watch?v=8g1mihnEmH0",
    },
    'Nasikabhushani': {
        arohanam:     ['Sa', 'Ri3', 'Ga3', 'Ma2', 'Pa', 'Da2', 'Ni2', 'Sa'],
        avarohanam:   ['Sa', 'Ni2', 'Da2', 'Pa', 'Ma2', 'Ga3', 'Ri3', 'Sa'],
        type:         'Melakarta 70',
        mood:         'Ornamentation · Delicacy',
        description:  'Named for a nose ornament  ·  delicate and precise. The compressed lower tetrachord with gentle upper notes and sharp Ma2 has a fineness to it.',
        compositions: [],
        color:        'teal',
        video:        "https://www.youtube.com/watch?v=OMPUEINaEHM",
    },
    'Kosalam': {
        arohanam:     ['Sa', 'Ri3', 'Ga3', 'Ma2', 'Pa', 'Da2', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Da2', 'Pa', 'Ma2', 'Ga3', 'Ri3', 'Sa'],
        type:         'Melakarta 71',
        mood:         'Grandeur · Royalty',
        description:  "Named for the ancient kingdom of Kosala (Rama's birthplace). Bright upper notes over the compressed lower tetrachord convey a regal, ancient grandeur.",
        compositions: [],
        color:        'teal',
        video:        "https://www.youtube.com/watch?v=U0p_Ky9bS5Y",
    },
    'Rasikapriya': {
        arohanam:     ['Sa', 'Ri3', 'Ga3', 'Ma2', 'Pa', 'Da3', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Da3', 'Pa', 'Ma2', 'Ga3', 'Ri3', 'Sa'],
        type:         'Melakarta 72',
        mood:         'Connoisseur · Joy',
        description:  'The 72nd and final Melakarta  ·  "dear to the connoisseur." Consecutive semitone pairs in both registers with sharp Ma2: the raga that rewards careful listening. A fitting end to the complete system.',
        compositions: [],
        color:        'teal',
        video:        "https://www.youtube.com/watch?v=H4jnX1XRP9o",
    },

    // ── Janya (derived) ragas ─────────────────────────────────────────────
    'Mohanam': {
        arohanam:     ['Sa', 'Ri2', 'Ga3', 'Pa', 'Da2', 'Sa'],
        avarohanam:   ['Sa', 'Da2', 'Pa', 'Ga3', 'Ri2', 'Sa'],
        type:         'Janya · Harikambhoji (28)',
        mood:         'Joy · Romance',
        description:  'Pentatonic and universally beloved  ·  this is the raga people hum without knowing it. Pure joy, wonder, and the sweetness of longing from a distance.',
        compositions: ['Sami Ninne  ·  Tyagaraja', 'Mohanam Geetham'],
        color:        'navy',
        video:        "https://www.youtube.com/watch?v=mcX9wjI6HvY",
    },
    'Hamsadhwani': {
        arohanam:     ['Sa', 'Ri2', 'Ga3', 'Pa', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Pa', 'Ga3', 'Ri2', 'Sa'],
        type:         'Janya · Shankarabharanam (29)',
        mood:         'Auspiciousness · Joy',
        description:  "The swan's voice. Bright, auspicious, and joyful  ·  played at the start of concerts and ceremonies. Vatapi Ganapatim makes this raga sing for everyone who hears it.",
        compositions: ['Vatapi Ganapatim  ·  Dikshitar'],
        color:        'navy',
        video:        "https://www.youtube.com/watch?v=4dUKUNXJ7SY",
    },
    'Sahana': {
        arohanam:     ['Sa', 'Ri2', 'Ga3', 'Ma1', 'Pa', 'Ma1', 'Da2', 'Ni2', 'Sa'],
        avarohanam:   ['Sa', 'Ni2', 'Da2', 'Pa', 'Ma1', 'Ga3', 'Ri2', 'Ga3','Sa'],
        type:         'Janya · Harikambhoji (28)',
        mood:         'Devotion · Pathos',
        description:  "Patience and endurance  ·  that's what sahana means. A raga of quiet strength, love that persists despite difficulty.",
        compositions: ['Sada Palayamam  ·  Dikshitar'],
        color:        'teal',
        video:        "https://www.youtube.com/shorts/2KNyiaqoWJ8",
    },
    'Kalyana Vasantham': {
        arohanam:     ['Sa', 'Ga2', 'Ma1', 'Da1', 'Ni3', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Da1', 'Pa', 'Ma1', 'Ga2', 'Ri2', 'Sa'],
        type:         'Janya · Keeravani (21)',
        mood:         'Bliss · Spring',
        description:  'Spring-time bliss  ·  a joyful, rare pentatonic ascending that skips notes in surprising ways. The kind of raga that makes you smile immediately.',
        compositions: ['Kalyana Vasantham Geetham'],
        color:        'maroon',
        video:        'https://www.youtube.com/shorts/zGZ0XxaYzIw',
    },
    'Bowli': {
        arohanam:     ['Sa', 'Ri1', 'Ga3', 'Pa', 'Da1', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Da1', 'Pa', 'Ga3', 'Ri1', 'Sa'],
        type:         'Janya · Mayamalavagowla (15)',
        mood:         'Morning · Devotion',
        description:  'A classic early morning raga. Invokes waking up to fresh morning dew and temple bells. Famous for MS Subbulakshmi\'s Sriman Narayana.',
        compositions: ['Sriman Narayana'],
        color:        'teal',
        video:        "https://www.youtube.com/shorts/SkN4LQUuRJw",
    },
    'Bhairavi': {
        arohanam:     ['Sa', 'Ri2', 'Ga2', 'Ma1', 'Pa', 'Da2', 'Ni2', 'Sa'], // Bhashanga: Da2 in ascent
        avarohanam:   ['Sa', 'Ni2', 'Da1', 'Pa', 'Ma1', 'Ga2', 'Ri2', 'Sa'],
        type:         'Janya · Natabhairavi (20)',
        mood:         'Pathos · Devotion',
        description:  "A raga that holds entire lifetimes of emotion. Bhairavi is sung at the end of concerts as a farewell  ·  because once you've heard it, nothing else needs to be said.",
        compositions: ['Viriboni  ·  Pachimiriam Adiyappaiah'],
        color:        'navy',
        video:        "https://www.youtube.com/watch?v=TgCPwgDYf4k",
    },
    'Kamboji': {
        arohanam:     ['Sa', 'Ri2', 'Ga3', 'Ma1', 'Pa', 'Da2', 'Sa'],
        avarohanam:   ['Sa', 'Ni2', 'Da2', 'Pa', 'Ma1', 'Ga3', 'Ri2', 'Sa'],
        type:         'Janya · Harikambhoji (28)',
        mood:         'Devotion · Heroism',
        description:  "A raga of temples and processions  ·  heroic devotion, the feeling of walking toward something sacred. The avarohanam's Ni2 (vakra) is its signature fingerprint.",
        compositions: ['Sarasamulanu  ·  Tyagaraja'],
        color:        'teal',
        video:        "https://www.youtube.com/watch?v=UiacgqG4ZTg",
    },
    'Todi': {
        arohanam:     ['Sa', 'Ri1', 'Ga2', 'Ma1', 'Pa', 'Da1', 'Ni2', 'Sa'],
        avarohanam:   ['Sa', 'Ni2', 'Da1', 'Pa', 'Ma1', 'Ga2', 'Ri1', 'Sa'],
        type:         'Janya · Hanumatodi (8)',
        mood:         'Pathos · Morning',
        description:  'The raga of early mornings and deep feeling. Todi holds sadness beautifully  ·  not wallowing in it, but sitting with it until it becomes something like peace.',
        compositions: ['Ninnukori  ·  Tyagaraja', 'Brovavamma  ·  Tyagaraja'],
        color:        'maroon',
        video:        "https://www.youtube.com/watch?v=nRvU1E3d9Sc",
    },
    'Saveri': {
        arohanam:     ['Sa', 'Ri1', 'Ma1', 'Pa', 'Da1', 'Sa'],
        avarohanam:   ['Sa', 'Ni3', 'Da1', 'Pa', 'Ma1', 'Ga3', 'Ri1', 'Sa'],
        type:         'Janya · Mayamalavagowla (15)',
        mood:         'Pathos · Compassion',
        description:  "Ancient and compassionate  ·  Saveri's pentatonic ascent feels simple until you realise how much it says with so few notes. A beautiful derivative of Mayamalavagowla.",
        compositions: ['Brochevarevarura  ·  Mysore Vasudevachar', 'Tulasi Jagajjanani  ·  Tyagaraja'],
        color:        'navy',
        video:        "https://www.youtube.com/watch?v=4ZmZhyCScJ8",
    },
    'Hindolam': {
        arohanam:     ['Sa', 'Ga2', 'Ma1', 'Da1', 'Ni2', 'Sa'],
        avarohanam:   ['Sa', 'Ni2', 'Da1', 'Ma1', 'Ga2', 'Sa'],
        type:         'Janya · Pentatonic',
        mood:         'Yearning · Night',
        description:  'Five notes and a universe of feeling. Hindolam is the raga of deep night and unresolved longing  ·  sung after midnight, when everything is quiet and the heart speaks.',
        compositions: ['Alamelumanga  ·  Tyagaraja'],
        color:        'teal',
        video:        "https://www.youtube.com/shorts/u3jlboz5CwY",
    },
    'Madhyamavati': {
        arohanam:     ['Sa', 'Ri2', 'Ma1', 'Pa', 'Ni2', 'Sa'],
        avarohanam:   ['Sa', 'Ni2', 'Pa', 'Ma1', 'Ri2', 'Sa'],
        type:         'Janya · Kharaharapriya (22)',
        mood:         'Peaceful · Auspicious',
        description:  'A majestic pentatonic scale (Audava) that traditionally concludes concerts. Its open fifths and skipping of Ga and Da create a sense of deep stability and resolution. One of the most auspicious ragas in the system.',
        compositions: ['Palukavemi Daivama  ·  Tyagaraja', 'Bhagyada Lakshmi Baramma  ·  Purandara Dasa'],
        color:        'teal',
        video:        "https://www.youtube.com/shorts/uUS2QppUZc8",
    },
    'Abheri': {
        arohanam:     ['Sa', 'Ga2', 'Ma1', 'Pa', 'Ni2', 'Sa'], // skips Ri and Da in ascent
        avarohanam:   ['Sa', 'Ni2', 'Da2', 'Pa', 'Ma1', 'Ga2', 'Ri2', 'Sa'],
        type:         'Janya · Kharaharapriya (22)',
        mood:         'Devotion · Serenity',
        description:  'A raga for still waters  ·  peaceful, devotional, clear. Nagumomu Ganaleni is one of the most beloved Carnatic compositions, and Abheri carries it perfectly.',
        compositions: ['Nagumomu  ·  Tyagaraja'],
        color:        'maroon',
        video:        "https://www.youtube.com/watch?v=sVVRh05KGdo",
    },
    'Abhogi': {
        arohanam:     ['Sa', 'Ri2', 'Ga2', 'Ma1', 'Da2', 'Sa'],
        avarohanam:   ['Sa', 'Da2', 'Ma1', 'Ga2', 'Ri2', 'Sa'],
        type:         'Janya · Kharaharapriya (22)',
        mood:         'Devotion · Pleading',
        description:  'A deeply emotive asymmetric pentatonic scale missing Pa and Ni. Without the stabilizing fifth (Pa), Abhogi feels restless and reaching, making it perfect for intense devotional pleading.',
        compositions: ['Sabhapatikku  ·  Gopalakrishna Bharathi', 'Evari Bodhana (Varnam)  ·  Patnam Subramania Iyer'],
        color:        'navy',
        video:        "https://www.youtube.com/watch?v=yTD1q8GvXT0",
    },
    'Durga': {
        arohanam:     ['Sa', 'Ri2', 'Ma1', 'Pa', 'Da2', 'Sa'],
        avarohanam:   ['Sa', 'Da2', 'Pa', 'Ma1', 'Ri2', 'Sa'],
        type:         'Janya · Pentatonic',
        mood:         'Joy · Auspiciousness',
        description:  'Five bright notes  ·  Durga is used in auspicious settings because of its bright, open quality. Close to the Western pentatonic major scale that appears in folk music across the world.',
        compositions: ['Durgamba  ·  Dikshitar'],
        color:        'teal',
        video:        "https://www.youtube.com/shorts/9s6vS8Mpi_A",
    },
    'Revati': {
        arohanam:     ['Sa', 'Ri1', 'Ma1', 'Pa', 'Ni2', 'Sa'],
        avarohanam:   ['Sa', 'Ni2', 'Pa', 'Ma1', 'Ri1', 'Sa'],
        type:         'Janya · Pentatonic',
        mood:         'Peaceful · Evening',
        description:  "Simple, pentatonic, and quietly beautiful. Revati doesn't demand  ·  it simply settles in the ear like evening light.",
        compositions: ['Palukavemiridam  ·  Tyagaraja'],
        color:        'maroon',
        video:        "https://www.youtube.com/watch?v=qKL7YIawcGM",
    },
    'Margahindolam': {
        arohanam:     ['Sa', 'Ri2', 'Ga2', 'Ma1', 'Pa', 'Da2', 'Ni2', 'Sa'],
        avarohanam:   ['Sa', 'Ni2', 'Da2', 'Pa', 'Ma1', 'Ga2', 'Sa'],
        type:         'Janya · Kharaharapriya (22)',
        mood:         'Devotion · Serenity',
        description:  "The avarohanam skips Sa's Ri entirely, giving it a characteristically smooth, rolling descent. Gentle and inward, like a slow morning walk to the temple. There is no youtube video of the arohanam and avarohanam but this video shares some notes in the raagam.",
        compositions: ['Chalamelara Saketha Rama'],
        color:        'navy',
        video:        "https://www.youtube.com/shorts/UbrC2vHCOp4",
    },
};

// noteFrequencies: optional map of {note: count} from the rolling pitch history.
export const identifyRaga = (detectedSwarams, noteFrequencies = {}) => {
    const uniqueNotes = new Set(detectedSwarams);
    let candidates = [];

    for (const [name, data] of Object.entries(RAGAS)) {
        const ragaNotes = new Set([...data.arohanam, ...data.avarohanam]);

        let matchCount = 0;
        let alienCount = 0;

        uniqueNotes.forEach(note => {
            if (ragaNotes.has(note)) matchCount++;
            else alienCount++;
        });

        if (matchCount < 4 || alienCount > 2) continue;

        // Arohanam prominence: are the arohanam notes sung more than average?
        // Janya ragas with skip notes score higher when those skipped notes are rare.
        const arohanamSet = new Set(data.arohanam);
        const arohanamNotes = data.arohanam.filter(n => n !== 'Sa');
        const avgArohanamFreq = arohanamNotes.length
            ? arohanamNotes.reduce((s, n) => s + (noteFrequencies[n] || 0), 0) / arohanamNotes.length
            : 0;
        const avgDetectedFreq = [...uniqueNotes].filter(n => n !== 'Sa')
            .reduce((s, n) => s + (noteFrequencies[n] || 0), 0) / Math.max(uniqueNotes.size - 1, 1);
        const arohanamProminence = avgDetectedFreq > 0 ? avgArohanamFreq / avgDetectedFreq : 1;

        // Vakra penalty: notes that appear in avarohanam but NOT arohanam should be rare.
        // If they're sung frequently, this raga is a worse fit (those notes should only appear in descent).
        const vakraNotes = data.avarohanam.filter(n => !arohanamSet.has(n) && n !== 'Sa');
        const avgVakraFreq = vakraNotes.length
            ? vakraNotes.reduce((s, n) => s + (noteFrequencies[n] || 0), 0) / vakraNotes.length
            : 0;
        const vakraPenalty = avgArohanamFreq > 0 ? avgVakraFreq / avgArohanamFreq : 0;

        const coverage = matchCount / ragaNotes.size;
        const score = (matchCount * 1.5) - (alienCount * 2) + (arohanamProminence * 0.6) - (vakraPenalty * 0.3);

        candidates.push({ name, ...data, score, coverage, matchCount, alienCount });
    }

    candidates.sort((a, b) => b.score - a.score);
    return candidates;
};
